# To use this config, FLINK_CONF_DIR env. var should be set.

# This is needed to prevent a "Insufficient number of network buffers"
# exceptions when running the merger on large input with many workers.
taskmanager.memory.network.max: 5gb

# This is to make pipeline.run() non-blocking with FlinkRunner; unfortunately
# this is overwritten in `local` mode: https://stackoverflow.com/a/74416240
execution.attached: false

# This is required to track the pipeline metrics when FlinkRunner is used.
execution.job-listeners: com.google.fhir.analytics.metrics.FlinkJobListener