name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/openmrs-fhir-analytics
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.PKG_USER }}
        password: ${{ secrets.PKG_TOKEN }}

    - name: Publish Docker image
      uses: docker/build-push-action@v2
      with:
        file: pipelines/streaming-binlog/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta2
    #   uses: docker/metadata-action@v3
    #   with:
    #     images: ${{ env.REGISTRY }}/openmrs-fhir-analytics/streaming-atomfeed

    # - name: Publish Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     file: pipelines/streaming-atomfeed/Dockerfile
    #     push: true
    #     tags: ${{ steps.meta2.outputs.tags }}
    #     labels: ${{ steps.meta2.outputs.labels }}
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max